Agah/urls.py
from django.urls import path
from Agah import views

urlpatterns = [
    path('personal/', views.Personal, name='personal'),
    path('children/', views.Children, name='children'),
    path('main/', views.Main_view, name='main'),
]

Portfolio/urls.py
from django.urls import path

from Portfolio import views

app_name = 'Portfolio'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>', views.ProfileUpdateView.as_view(), name='Profile'),
    path('job/', views.JobCreate.as_view(), name='job_create'),
    path('job/update/<int:pk>', views.JobUpdate.as_view(), name='job_update'),
    path('job/remove/<int:pk>', views.JobDelete, name='job_delete'),
    path('skill/', views.SkillCreate.as_view(), name='skill_create'),
    path('skill/update/<int:pk>', views.SkillUpdate.as_view(), name='skill_update'),
    path('skill/remove/<int:pk>', views.SkillDelete, name='skill_delete'),
    path('education/', views.EducationCreate.as_view(), name='education_create'),
    path('education/update/<int:pk>', views.EducationUpdate.as_view(), name='education_update'),
    path('education/remove/<int:pk>', views.EducationDelete, name='education_delete'),
    path('language/', views.LanguageCreate.as_view(), name='language_create'),
    path('language/update/<int:pk>', views.LanguageUpdate.as_view(), name='language_update'),
    path('language/remove/<int:pk>', views.LanguageDelete, name='language_delete'),
    path('certificate/', views.CertificateCreate.as_view(), name='certificate_create'),
    path('certificate/update/<int:pk>', views.CertificateUpdate.as_view(), name='certificate_update'),
    path('certificate/remove/<int:pk>', views.CertificateDelete, name='certificate_delete'),
    path('<str:username>/', views.Protfolio, name='portfolio_with_username'),
    path('', views.Protfolio, name='portfolio')
]

Portfolio/forms.py
import django.forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from Agah import forms
from Portfolio.models import Profile, Job, Skill, Education, Language, Certificate


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']


class DateInput(django.forms.DateInput):
    input_type = 'date'


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['gender', 'marital_status', 'birthday', 'occupation', 'country', 'city', 'image', 'about_me', 'title',
                  'phone', 'address']
        widgets = {
            'birthday': DateInput()
        }


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ['profile']
        widgets = {
            'already_work': django.forms.CheckboxInput,
            'start_dte': DateInput(),
            'end_dte': DateInput(),
        }


class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        exclude = ['profile']


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ['title', 'university', 'from_dte', 'to_dte', 'grade', 'degree']
        widgets = {
            'from_dte': DateInput(),
            'to_dte': DateInput(),
        }


class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        exclude = ['profile']


class CertificateForm(forms.ModelForm):
    class Meta:
        model = Certificate
        exclude = ['profile']
        widgets = {
            'date': DateInput(),
            'have_cert': django.forms.CheckboxInput
        }

Portfolio/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from Portfolio.forms import RegisterForm, ProfileUpdateForm, JobForm, SkillForm, EducationForm, LanguageForm, \
    CertificateForm
from Portfolio.models import Profile, Job, Skill, Education, Language, Certificate


class RegisterView(CreateView):
    template_name = 'Portfolio/Account/Register.html'
    form_class = RegisterForm

    def get_success_url(self):
        return reverse_lazy('Portfolio:Profile', kwargs={'pk': self.request.user.profile.pk})


class LoginView(LoginView):
    template_name = 'Portfolio/Account/Login.html'


class LogoutView(LogoutView):
    pass


class ProfileUpdateView(UpdateView):
    model = Profile
    template_name = 'Portfolio/Profile/Update.html'
    form_class = ProfileUpdateForm

    def post(self, request, *args, **kwargs):
        profile = get_object_or_404(Profile, pk=kwargs.get('pk'))
        if profile.user != request.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})

        form = ProfileUpdateForm(request.POST, instance=profile, files=request.FILES)
        if form.is_valid():
            form.save()
        return redirect(reverse('Portfolio:portfolio'))


class JobCreate(CreateView):
    model = Job
    form_class = JobForm
    template_name = 'Portfolio/Job/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        form = JobForm(request.POST)
        if form.is_valid():
            job = form.save(commit=False)
            job.profile = request.user.profile
            job.save()
            return redirect(reverse('Portfolio:portfolio'))


class JobUpdate(UpdateView):
    model = Job
    form_class = JobForm
    template_name = 'Portfolio/Job/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        job = Job.objects.get(pk=kwargs.get('pk'))
        if request.user != job.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        form = JobForm(request.POST, instance=job)
        if form.is_valid():
            form.save()
            return redirect(reverse('Portfolio:portfolio'))


def JobDelete(request, pk):
    if request.method == 'GET':
        job = get_object_or_404(Job, pk=pk)
        if request.user != job.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        job.delete()
        return redirect(reverse('Portfolio:portfolio'))


class SkillCreate(CreateView):
    model = Skill
    form_class = SkillForm
    template_name = 'Portfolio/Skill/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.profile = request.user.profile
            skill.save()
            return redirect(reverse('Portfolio:portfolio'))


class SkillUpdate(UpdateView):
    model = Skill
    form_class = SkillForm
    template_name = 'Portfolio/Skill/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        skill = Skill.objects.get(pk=kwargs.get('pk'))
        if request.user != skill.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            return redirect(reverse('Portfolio:portfolio'))


def SkillDelete(request, pk):
    if request.method == 'GET':
        skill = get_object_or_404(Skill, pk=pk)
        if request.user != skill.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        skill.delete()
        return redirect(reverse('Portfolio:portfolio'))


class EducationCreate(CreateView):
    model = Education
    form_class = EducationForm
    template_name = 'Portfolio/Education/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        form = EducationForm(request.POST)
        if form.is_valid():
            education = form.save(commit=False)
            education.profile = request.user.profile
            education.save()
            return redirect(reverse('Portfolio:portfolio'))


class EducationUpdate(UpdateView):
    model = Education
    form_class = EducationForm
    template_name = 'Portfolio/Education/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        education = Education.objects.get(pk=kwargs.get('pk'))
        if request.user != education.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        form = EducationForm(request.POST, instance=education)
        if form.is_valid():
            form.save()
            return redirect(reverse('Portfolio:portfolio'))


def EducationDelete(request, pk):
    if request.method == 'GET':
        education = get_object_or_404(Education, pk=pk)
        if request.user != education.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        education.delete()
        return redirect(reverse('Portfolio:portfolio'))


class LanguageCreate(CreateView):
    model = Language
    form_class = LanguageForm
    template_name = 'Portfolio/Language/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        form = LanguageForm(request.POST)
        if form.is_valid():
            language = form.save(commit=False)
            language.profile = request.user.profile
            language.save()
            return redirect(reverse('Portfolio:portfolio'))


class LanguageUpdate(UpdateView):
    model = Language
    form_class = LanguageForm
    template_name = 'Portfolio/Language/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        language = Language.objects.get(pk=kwargs.get('pk'))
        if request.user != language.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        form = LanguageForm(request.POST, instance=language)
        if form.is_valid():
            form.save()
            return redirect(reverse('Portfolio:portfolio'))


def LanguageDelete(request, pk):
    if request.method == 'GET':
        language = get_object_or_404(Language, pk=pk)
        if request.user != language.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        language.delete()
        return redirect(reverse('Portfolio:portfolio'))


class CertificateCreate(CreateView):
    model = Certificate
    form_class = CertificateForm
    template_name = 'Portfolio/Certificate/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        form = CertificateForm(request.POST, files=request.FILES)
        if form.is_valid():
            certificate = form.save(commit=False)
            certificate.profile = request.user.profile
            certificate.save()
            return redirect(reverse('Portfolio:portfolio'))


class CertificateUpdate(UpdateView):
    model = Certificate
    form_class = CertificateForm
    template_name = 'Portfolio/Certificate/CreateAndUpdate.html'

    def post(self, request, *args, **kwargs):
        certificate = Certificate.objects.get(pk=kwargs.get('pk'))
        if request.user != certificate.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        form = CertificateForm(request.POST, instance=certificate, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('Portfolio:portfolio'))


def CertificateDelete(request, pk):
    if request.method == 'GET':
        certificate = get_object_or_404(Certificate, pk=pk)
        if request.user != certificate.profile.user:
            return render(request, 'Portfolio/error.html', context={'error_title': 'Access denied!',
                                                                    'error': ' only profile owner can update this profile'})
        certificate.delete()
        return redirect(reverse('Portfolio:portfolio'))


def PortfolioView(request):
    if request.method == 'GET':
        pass


def Protfolio(request, username=None):
    if request.method == 'GET':
        show_control_box = False
        try:
            user = get_object_or_404(User, username=username)
        except:

templates/Portfolio/Register.html
{% extends 'Portfolio/base.html' %}
{% block title %}
    Register
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="first_name">Firstname</label>
                {{ form.first_name }}
            </div>
            <div class="form-group col-md-6">
                <label for="last_name">Lastname</label>
                {{ form.last_name }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="email">Email</label>
                {{ form.email }}
            </div>
            <div class="form-group col-md-6">
                <label for="username">Username</label>
                {{ form.username }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="password1">Password</label>
                {{ form.password1 }}
            </div>
            <div class="form-group col-md-6">
                <label for="password2">Confirm Password</label>
                {{ form.password2 }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
{% endblock %}

templates/Portfolio/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <style>
        .wrapper {
            margin-top: 20px;
            margin-bottom: 20px;
            background-color: white;
            padding: 15px;
            border-radius: 7px;
            width: 100%;
        }

        .content {
            width: 100%;
            background-color: lightgray;
            border-radius: 7px;
            width: 100%;
            padding: 7px;
        }

        .side {
            margin-left: 10px;
        }

        .container {
            margin-top: 90px;
        }
    </style>
    {#    bootstrap4#}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% block extra_header %}{% endblock %}
</head>
<body>

<div class="container">
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">{% if user.is_authenticated %}
            {{ user.get_username }}
        {% endif %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'Portfolio:logout' %}">Logout <span
                                class="sr-only">(current)</span></a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'Portfolio:register' %}">Register <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'Portfolio:login' %}">Login <span
                                class="sr-only">(current)</span></a>
                    </li>

                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
            </ul>
        </div>
    </nav>
    {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% for error in form.errors.values %}
                <strong>{{ error }}</strong>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-12 content side">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
<script type="application/javascript">
    $('input').addClass('form-control')
    $('textarea').addClass('form-control')
    $('select').addClass('custom-select')
    $('input[type=file]').removeClass('form-control')
    $('input[type=checkbox]').removeClass('form-control')
    $('input[type=checkbox]').addClass('form-check-input')
</script>
{% block extra_js %}
{% endblock %}
</body>
</html>

templates/Portfolio/error.html
{% extends 'Portfolio/base.html' %}
{% block title %}
    {{ error_title }}
{% endblock %}
{% block content %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h3>
            <strong>{{ error_title }}</strong>
            {{ error }}
        </h3>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endblock %}